language: node_js
node_js:
  - "5.0"
  - "4.2"
before_script:
  - npm install -g bower gulp istanbul
  - bower install
script:
  - gulp ci
  - npm test
  - npm run nsp
  - npm run -s lint
  - npm run -s jsinspect
  - npm run coverage